sudo: required
dist: trusty

language: python
python:
  - 3.4
  - 3.5
  - 3.6

env:
  - TOX_ENV=flake8

before_install:
before_install:
  - sudo apt-get update
  - sudo apt-get install chromium-chromedriver  # chrome v64.0

before_script:
  - "export PATH=$PATH:/usr/lib/chromium-browser/"
  - "export DISPLAY=:99.0" 
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

install: 
  - pip install -U tox-travis
  - pip install codecov

script:
  - tox -e $TOX_ENV
  - tox

after_success:
  - codecov

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: giannis.terzopoulos
  password:
    secure: JOA3DG4tqdmDGp5dwugdTZZ7u29ILOTeAxIgf8QmzcSvGRVt1B9yP8OVq3gX5YtFDf5D+tVm3BsR6kiYrS54qZ7cmWXcC+QB8vN4g9AGh3FN3LJ4CuvxG5E4rhZtkFPGfMB0TmCmV9/HbmSHtPLKsIKMTZSVQAuAg3XFgmryrj8r4jdE7Ryzp7BK2iAFz60Ajq7u7qOjHZyTtpoVsj1W8SsBREE0UA7fJsz2X+GazqWeGv78hVT4ft9mWahrR3LtSyLqq54ani4NIgOCtrSc/H4vlGV2t/RA1mIX50S5XY5gmdAvhuu1j35Q2HpihsSh2HE9n+TBAp7IigzghKXZJ8cKnQWiDxtQPQsdlGov5oGUt5YJLUDFZ8njE73ZQpkYb4MIL++lnEf/sgm+tMap9FF2068nfqwt+nRN223NkxA1Mb7t6KeEiSG7L1W9QY3D+lJesEvLNp0+49vzPmdJXn4/Pszvwl0A4K8PXekZNqEeXSHrup8xJa2ex1vCIw8ZjO2f/zTvA5azkK436/KmQJilJeVZ8yiBuEgX+mKYsJWuOLNFad7i5x5TpjYSOvQQ3MPEld8m9RYwG5AxGsvFlY0mlPE5a+6rqfSh0ijISC7FB41+spK4OLtx8zpnP4NDPMFCTIkXru2RuP4kBXVP/DIucVBHzPaBwrfHt7vYCnw=
  on:
    tags: true
    repo: giannisterzopoulos/scribd-dl
    branch: master
    python: 3.6
